#!/usr/bin/env node

/**
 * The edge's cache policy, written from the artifact that declares it.
 *
 * `dist/web/artifact.json` carries a cache class per emitted file and the header
 * string per class. nginx is a second adapter over that same declaration, and for
 * as long as it was hand-written beside the artifact the two could disagree
 * without anything noticing: `/i18n/` kept a location of its own after the build
 * started hashing locale bundles into `/assets/`, and `/media/` sent two
 * Cache-Control headers for a browser to reconcile.
 *
 * So the half of `deploy/nginx.conf.example` that states a Cache-Control is
 * generated from `report.cache` rather than written next to it. `npm run nginx`
 * rewrites the region between the two markers; `npm run nginx -- --check` fails
 * when the file has drifted from the artifact, which is the step the deploy runs
 * after the build. Everything outside the markers -- the TLS, the proxy
 * settings, the upstream, `/media/` -- is hand-written and untouched.
 *
 * Grouping is by the first path segment, and every artifact file that shares one
 * must share a cache class: a directory becomes one `^~` prefix location, a file
 * at the root becomes one `=` exact location. `^~` rather than a plain prefix
 * because of the guard below it -- a regex location outranks an ordinary prefix
 * one, and `/assets/app-root-*.js` must not be answered by the rule that exists
 * to 404 file-shaped paths.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const CONFIG = 'deploy/nginx.conf.example';
const ARTIFACT = 'dist/web/artifact.json';

const BEGIN = '    # ── BEGIN generated by tools/deploy/nginx.mjs ─────────────────────────────';
const END = '    # ── END generated ─────────────────────────────────────────────────────────';

/**
 * Repeated in every location that sets a header of its own, because one
 * `add_header` in a location drops every `add_header` the server block set. See
 * the top of the config.
 */
const SECURITY = [
  'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;',
  'add_header X-Content-Type-Options    "nosniff" always;',
  'add_header Referrer-Policy           "strict-origin-when-cross-origin" always;',
  'add_header X-Frame-Options           "DENY" always;',
];

/**
 * A path that ends in one of these and is not on disk is a mistake, not a client
 * route, and answering it with the application shell makes `artifact.json`,
 * `release.json` and every internal name look like a page that exists. The list
 * is extensions, not `\.[a-z]+$`, so a slug with a dot in it stays a route.
 */
const FILE_EXTENSIONS =
  'avif|css|gif|ico|jpe?g|js|json|map|md|mjs|png|svg|txt|wasm|webp|woff2?|xml';

/** @param {string} head @param {string[]} lines */
function block(head, lines) {
  return [`    ${head} {`, ...lines.map((line) => `        ${line}`), '    }'].join('\n');
}

/** @param {string} artifactRoot */
function policy(artifactRoot) {
  const report = JSON.parse(readFileSync(resolve(artifactRoot), 'utf8'));

  /** @type {Map<string, { kind: 'prefix' | 'exact', cache: string }>} */
  const groups = new Map();
  for (const file of report.files) {
    if (!file.path.startsWith('public/')) continue;
    const rest = file.path.slice('public/'.length);
    const slash = rest.indexOf('/');
    const kind = slash === -1 ? 'exact' : 'prefix';
    const key = slash === -1 ? `/${rest}` : `/${rest.slice(0, slash)}/`;
    const seen = groups.get(key);
    if (seen === undefined) {
      groups.set(key, { kind, cache: file.cache });
      continue;
    }
    if (seen.cache !== file.cache) {
      throw new Error(
        `nginx: ${key} holds both "${seen.cache}" and "${file.cache}" files, ` +
          'so it cannot be one location. Split it in the build or teach this tool the split.',
      );
    }
  }

  const header = (/** @type {string} */ cache) => {
    const value = report.cache[cache];
    if (typeof value !== 'string') {
      throw new Error(`nginx: cache class "${cache}" has no header string in the artifact.`);
    }
    return value;
  };

  const document = groups.get('/index.html');
  if (document === undefined) {
    throw new Error('nginx: the artifact has no public/index.html, so no document policy to state.');
  }

  const keys = [...groups.keys()].sort();
  const prefixes = keys.filter((key) => groups.get(key)?.kind === 'prefix');
  const exacts = keys.filter((key) => groups.get(key)?.kind === 'exact');

  return [
    BEGIN,
    '    # Every Cache-Control below is report.cache[class] verbatim. No `expires`',
    '    # beside one: that directive writes a Cache-Control of its own, and a location',
    '    # setting both sends two of them.',
    '',
    ...prefixes.flatMap((key) => {
      const cache = header(/** @type {string} */ (groups.get(key)?.cache));
      return [
        block(`location ^~ ${key}`, [
          `add_header Cache-Control "${cache}";`,
          ...SECURITY,
          'access_log off;',
        ]),
        '',
      ];
    }),
    ...exacts.flatMap((key) => {
      const cache = header(/** @type {string} */ (groups.get(key)?.cache));
      return [block(`location = ${key}`, [`add_header Cache-Control "${cache}";`, ...SECURITY]), ''];
    }),
    `    # A file-shaped path that is not on disk is 404, not the shell.`,
    block(`location ~* ^/.+\\.(?:${FILE_EXTENSIONS})$`, ['try_files $uri =404;']),
    '',
    '    # Everything else is a route, and the application answers it with index.html',
    '    # plus the per-URL title and og: tags app/seo.py injects. Same document, so',
    '    # the same class the artifact gives index.html.',
    block('location /', ['try_files $uri @app;']),
    '',
    block('location @app', [
      'proxy_pass http://santella_api;',
      '# The application sets these four itself, because in development it is the',
      '# whole stack with no nginx in front of it, and `add_header` appends to what',
      '# the upstream sent rather than replacing it. `proxy_hide_header` has the same',
      '# inheritance rule as `add_header`, so naming one here drops the server',
      "# block's three and all four have to be written out.",
      'proxy_hide_header Cache-Control;',
      'proxy_hide_header X-Content-Type-Options;',
      'proxy_hide_header Referrer-Policy;',
      'proxy_hide_header X-Frame-Options;',
      `add_header Cache-Control "${header(document.cache)}" always;`,
      ...SECURITY,
    ]),
    END,
  ].join('\n');
}

const check = process.argv.includes('--check');
const configPath = resolve(CONFIG);
const current = readFileSync(configPath, 'utf8');
const begin = current.indexOf(BEGIN);
const end = current.indexOf(END);

if (begin === -1 || end === -1 || end < begin) {
  console.error(`nginx: ${CONFIG} has no generated region. Restore both marker lines.`);
  process.exit(1);
}

const next = `${current.slice(0, begin)}${policy(ARTIFACT)}${current.slice(end + END.length)}`;

if (next === current) {
  process.stdout.write(`nginx: ${CONFIG} matches ${ARTIFACT}\n`);
} else if (check) {
  console.error(
    `nginx: ${CONFIG} has drifted from ${ARTIFACT}. Run \`npm run nginx\` and commit the result.`,
  );
  process.exit(1);
} else {
  writeFileSync(configPath, next);
  process.stdout.write(`nginx: rewrote the generated region of ${CONFIG}\n`);
}
