import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

/**
 * Generate web/src/icons.js.
 *
 * Two families, because they render differently: lucide outlines are stroked,
 * simple-icons brand marks are filled. Both end up as one `d` string per name,
 * for the reason srl's example gives — Lit parses every template as HTML, so a
 * bare <path> outside an <svg> is an HTMLUnknownElement.
 *
 * Nothing here is authored by hand: lucide primitives are converted to path data
 * by the rules below, and brand paths are copied verbatim.
 */

const ROOT = resolve(import.meta.dirname, '../..');

const UI = [
  'sun', 'moon', 'monitor', 'pencil', 'check', 'x', 'plus', 'trash-2',
  'arrow-up', 'arrow-down', 'arrow-left', 'arrow-up-right', 'external-link',
  'mail', 'link', 'rss',
  'chevron-left', 'chevron-right', 'chevron-down', 'star', 'git-fork',
  'download', 'tag', 'calendar', 'map-pin', 'briefcase', 'copy', 'menu',
  'refresh-cw', 'log-out', 'log-in', 'image', 'crop', 'clock', 'globe',
];

const BRANDS = [
  'github', 'instagram', 'bandcamp', 'goodreads', 'paypal', 'vinted',
  'spotify', 'applemusic', 'discogs', 'youtube', 'soundcloud',
];

/** @param {string} name @returns {string} */
const camel = (name) => name.replace(/-([a-z0-9])/gu, (_, c) => c.toUpperCase());

/**
 * A subpath that means the same thing wherever it is pasted.
 *
 * Every icon here ends up as one `d` string, and a `d` that starts with a
 * *relative* moveto is only absolute when it is the first thing in a path. Paste
 * it after another subpath and it moves relative to wherever that one ended —
 * which is how `arrow-down` became a bare vertical bar with its head drawn at
 * (31, 31), off the 24-unit grid. Rewriting the leading `m` as `M` fixes the
 * origin; the implicit linetos that followed it have to be spelled `l`, or they
 * would turn absolute with it.
 *
 * @param {string} data
 * @returns {string}
 */
function fromOrigin(data) {
  const match = /^m\s*(-?[\d.]+)[\s,]+(-?[\d.]+)(.*)$/su.exec(data.trim());
  if (match === null) return data.trim();
  const [, x, y, rest] = match;
  const tail = rest.trimStart();
  if (tail === '') return `M${x} ${y}`;
  return /^[-+.\d]/u.test(tail) ? `M${x} ${y}l${tail}` : `M${x} ${y}${tail}`;
}

/**
 * @param {[string, Record<string, string>][]} nodes
 * @returns {string}
 */
function toPathData(nodes) {
  return nodes
    .map(([tag, attrs]) => {
      if (tag === 'path') return attrs.d;
      if (tag === 'line') return `M${attrs.x1} ${attrs.y1}L${attrs.x2} ${attrs.y2}`;
      if (tag === 'polyline' || tag === 'polygon') {
        const points = attrs.points.trim().split(/[\s,]+/u);
        const pairs = [];
        for (let i = 0; i < points.length; i += 2) pairs.push(`${points[i]} ${points[i + 1]}`);
        return `M${pairs.join('L')}${tag === 'polygon' ? 'Z' : ''}`;
      }
      if (tag === 'circle' || tag === 'ellipse') {
        const cx = Number(attrs.cx);
        const cy = Number(attrs.cy);
        const rx = Number(attrs.r ?? attrs.rx);
        const ry = Number(attrs.r ?? attrs.ry);
        // Two arcs, not one: a single 360-degree arc has identical endpoints and
        // renders nothing.
        return `M${cx - rx} ${cy}A${rx} ${ry} 0 1 0 ${cx + rx} ${cy}A${rx} ${ry} 0 1 0 ${cx - rx} ${cy}`;
      }
      if (tag === 'rect') {
        const x = Number(attrs.x);
        const y = Number(attrs.y);
        const w = Number(attrs.width);
        const h = Number(attrs.height);
        const r = Math.min(Number(attrs.rx ?? 0), w / 2, h / 2);
        if (r === 0) return `M${x} ${y}h${w}v${h}h${-w}Z`;
        return (
          `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}` +
          `v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}` +
          `h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}` +
          `v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}Z`
        );
      }
      throw new Error(`No conversion for <${tag}>`);
    })
    .map(fromOrigin)
    .join('');
}

const lucide = JSON.parse(await readFile(join(ROOT, 'node_modules/lucide-static/icon-nodes.json'), 'utf8'));
const simple = await import(join(ROOT, 'node_modules/simple-icons/index.mjs'));

/** @type {Record<string, string>} */
const ui = {};
for (const name of UI) {
  const nodes = lucide[name];
  if (nodes === undefined) throw new Error(`lucide has no icon "${name}"`);
  ui[camel(name)] = toPathData(nodes);
}

/** @type {Record<string, string>} */
const brands = {};
for (const slug of BRANDS) {
  const key = `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;
  const icon = simple[key];
  if (icon === undefined) throw new Error(`simple-icons has no "${slug}" (removed upstream?)`);
  brands[camel(slug)] = icon.path;
}

const body = `/**
 * GENERATED by tools/dev/icons.mjs. Do not edit.
 *
 * Two families because they render differently. UI outlines come from
 * lucide-static (ISC) and are stroked with currentColor on a 24x24 grid; brand
 * marks come from simple-icons (CC0) and are filled. Every icon is one \`d\`
 * string, which is what lets a template bind it as <path [d]="iconPath(name)">.
 */

/** @type {Readonly<Record<string, string>>} */
const UI_ICONS = ${JSON.stringify(ui, null, 2)};

/** @type {Readonly<Record<string, string>>} */
const BRAND_ICONS = ${JSON.stringify(brands, null, 2)};

/**
 * @param {string} name
 * @returns {string}
 */
export function iconPath(name) {
  return UI_ICONS[name] ?? '';
}

/**
 * A brand mark, falling back to the generic link glyph for brands simple-icons
 * does not carry — LinkedIn and Amazon were both removed upstream.
 *
 * @param {string} name
 * @returns {string}
 */
export function brandPath(name) {
  return BRAND_ICONS[name] ?? UI_ICONS.link;
}

/**
 * Whether \`name\` draws as a fill. A stroked brand mark is a smear and a filled
 * outline is a blob, so the template asks before choosing.
 *
 * @param {string} name
 * @returns {boolean}
 */
export function isBrand(name) {
  return name in BRAND_ICONS;
}
`;

await writeFile(join(ROOT, 'web/src/icons.js'), body);
process.stdout.write(`web/src/icons.js: ${String(Object.keys(ui).length)} ui, ${String(Object.keys(brands).length)} brand\n`);
